version: '3'
services:
  db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: expdb1
    environment:
      - ORACLE_PWD=mysecurepassword
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - ./oradata:/opt/oracle/oradata