version: '3'
services:
  ords:
    image: container-registry.oracle.com/database/ords:latest
    container_name: ords
    ports:
      - 8181:8181
    volumes:
      - ./ords_secrets/:/opt/oracle/variables